
[package]
name = "triad"
version = "0.1.0"
edition = "2021"
default-run = "triad"



[lib]
name = "triad"
path = "src/lib.rs"



[dependencies]
rand = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread","signal"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }
uuid = { version = "1", features = ["v4"] }
sha2 = "0.10"
hmac = "0.12"
futures-util = "0.3.31"
