# DIS-PERSONAL v0.5 configuration
default_domain: domain.null
default_scope: identity.confirm
signature_algorithm: sha256
database_path: data/dis.db
nonce_bytes: 16
policy_path: policy.yaml

# Network (v0.5)
api_host: 0.0.0.0   # 0.0.0.0 to accept LAN connections; 127.0.0.1 for local-only
api_port: 8080


verifyCore: true