# DIS-PERSONAL v0.5 configuration
default_domain: domain.null
default_scope: identity.confirm
signature_algorithm: sha256
database_path: data/dis.db
nonce_bytes: 16
policy_path: policy.yaml


verifyCore: true
